spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug  # ???? SQL ?? ??
      org.hibernate.orm.jdbc.bind: trace  # SQL ???? ???? ? ??



  spring:
    jpa:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl






